# Generated by Django 4.2.5 on 2023-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerseyno', models.CharField(help_text='jerseyno', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('YOE', models.IntegerField()),
            ],
        ),
    ]
